:objects rooma roomb - room
:objects ball39 ball38 ball37 ball36 ball35 ball34 ball33 ball32 ball31 ball30 ball29 ball28 ball27 ball26 ball25 ball24 ball23 ball22 ball21 ball20 ball19 ball18 ball17 ball16 ball15 ball14 ball13 ball12 ball11 ball10 ball9 ball8 ball7 ball6 ball5 ball4 ball3 ball2 ball1 - ball
:objects left right - gripper

:init enum at-robby rooma
:init enum at ball39 rooma
:init enum at ball38 rooma
:init enum at ball37 rooma
:init enum at ball36 rooma
:init enum at ball35 rooma
:init enum at ball34 rooma
:init enum at ball33 rooma
:init enum at ball32 rooma
:init enum at ball31 rooma
:init enum at ball30 rooma
:init enum at ball29 rooma
:init enum at ball28 rooma
:init enum at ball27 rooma
:init enum at ball26 rooma
:init enum at ball25 rooma
:init enum at ball24 rooma
:init enum at ball23 rooma
:init enum at ball22 rooma
:init enum at ball21 rooma
:init enum at ball20 rooma
:init enum at ball19 rooma
:init enum at ball18 rooma
:init enum at ball17 rooma
:init enum at ball16 rooma
:init enum at ball15 rooma
:init enum at ball14 rooma
:init enum at ball13 rooma
:init enum at ball12 rooma
:init enum at ball11 rooma
:init enum at ball10 rooma
:init enum at ball9 rooma
:init enum at ball8 rooma
:init enum at ball7 rooma
:init enum at ball6 rooma
:init enum at ball5 rooma
:init enum at ball4 rooma
:init enum at ball3 rooma
:init enum at ball2 rooma
:init enum at ball1 rooma

:goal enum at ball39 roomb
:goal enum at ball38 roomb
:goal enum at ball37 roomb
:goal enum at ball36 roomb
:goal enum at ball35 roomb
:goal enum at ball34 roomb
:goal enum at ball33 roomb
:goal enum at ball32 roomb
:goal enum at ball31 roomb
:goal enum at ball30 roomb
:goal enum at ball29 roomb
:goal enum at ball28 roomb
:goal enum at ball27 roomb
:goal enum at ball26 roomb
:goal enum at ball25 roomb
:goal enum at ball24 roomb
:goal enum at ball23 roomb
:goal enum at ball22 roomb
:goal enum at ball21 roomb
:goal enum at ball20 roomb
:goal enum at ball19 roomb
:goal enum at ball18 roomb
:goal enum at ball17 roomb
:goal enum at ball16 roomb
:goal enum at ball15 roomb
:goal enum at ball14 roomb
:goal enum at ball13 roomb
:goal enum at ball12 roomb
:goal enum at ball11 roomb
:goal enum at ball10 roomb
:goal enum at ball9 roomb
:goal enum at ball8 roomb
:goal enum at ball7 roomb
:goal enum at ball6 roomb
:goal enum at ball5 roomb
:goal enum at ball4 roomb
:goal enum at ball3 roomb
:goal enum at ball2 roomb
:goal enum at ball1 roomb